Fixed `UnboundLocalError`, which is pasted below.
```
Traceback (most recent call last):
  File "tabulate", line 309, in <module>
    _main()
  File "tabulate", line 297, in _main
    args.layout, args.strict)
  File "tabulate", line 239, in find_best_widths
    break_on_hyphens, strict))
  File "tabulate", line 228, in attempt_wrap
    return nrows_total, err
UnboundLocalError: local variable 'err' referenced before assignment
```